from __future__ import annotations

import typing

import numpy as np

import ufl
from mpi4py import MPI

from dolfinx.fem.bcs import DirichletBC
from dolfinx.fem.forms import Form
from dolfinx.fem.forms import form as _create_form
from dolfinx.fem.forms import extract_function_spaces
from dolfinx.fem.petsc import (assemble_vector, assemble_matrix, create_vector, create_matrix, set_bc, apply_lifting)
from dolfinx.fem.function import Function as _Function

from petsc4py import PETSc


class NonlinearProblem_mod:
    """Nonlinear problem class for solving the non-linear problem
    :math:`F(u, v) = 0 \\ \\forall v \\in V` using PETSc as the linear algebra
    backend.

    Copied from DOLFINx's built-in `NonlinearProblem` and extended with a
    caller-selectable Jacobian matrix type (`mat_type`, e.g. "baij" for
    point-block ILU).
    """

    def __init__(self, F: ufl.form.Form, J: ufl.form.Form, u: _Function, bcs: typing.List[DirichletBC] = [],
                 form_compiler_options={}, jit_options={}, mat_type: str = None):
        """Initialize solver for solving a non-linear problem using Newton's method, :math:`dF/du(u) du = -F(u)`.

        Args:
            F: The PDE residual F(u, v)
            u: The unknown
            bcs: List of Dirichlet boundary conditions
            J: UFL representation of the Jacobian (Optional)
            form_compiler_options: Options used in FFCx
                compilation of this form. Run ``ffcx --help`` at the
                commandline to see all available options.
            jit_options: Options used in CFFI JIT compilation of C
                code generated by FFCx. See ``python/dolfinx/jit.py``
                for all available options. Takes priority over all
                other option values.

        Example::

            problem = LinearProblem(F, u, [bc0, bc1])

        """
        # TODO: Figure out why form_compiler_options and jit_options below are unexpected keywords. 
        #       According to the DOLFINx 0.6.0 documentation this should be correct

        self._L = _create_form(F, form_compiler_options=form_compiler_options,
                               jit_options=jit_options)

        self.u = u

        # Create the Jacobian matrix, dF/du
        # if J is None:
        #     V = u.function_space
        #     du = ufl.TrialFunction(V)
        #     J = ufl.derivative(F, u, du)

        self._a = _create_form(J, form_compiler_options=form_compiler_options,
                               jit_options=jit_options)
        self.bcs = bcs

        # PETSc matrix type for the Jacobian (e.g. "baij" for point-block
        # ILU). None -> PETSc default (aij). self._A below is the one
        # full-space Jacobian: SNESNewtonSolver uses it directly as its
        # operator.
        self.mat_type = mat_type

        # save some vectors and matrices with appropriate sparsity structures for use later
        self._A = create_matrix(self.a, kind=self.mat_type)
        self._b = create_vector(extract_function_spaces(self.L))

    @property
    def L(self) -> Form:
        """Compiled linear form (the residual form)"""
        return self._L

    @property
    def a(self) -> Form:
        """Compiled bilinear form (the Jacobian form)"""
        return self._a

    def form(self, x: PETSc.Vec):
        """
        This function is called before the residual or Jacobian is
        computed. This is usually used to update ghost values.

        Args:
           x: The vector containing the latest solution

        """
        # print("Call form in NonlinearProblem_mod")
        # PETSc.Sys.Print("u pre norm: {}".format(self.u.x.petsc_vec.norm()))
        x.ghostUpdate(addv=PETSc.InsertMode.INSERT, mode=PETSc.ScatterMode.FORWARD)
        x.copy(self.u.x.petsc_vec)
        # PETSc.Sys.Print("u post norm: {}".format(self.u.x.petsc_vec.norm()))

    def F(self, x: PETSc.Vec, b: PETSc.Vec):
        """
        Assemble the residual F into the vector b.

        Args:
            x: The vector containing the latest solution
            b: Vector to assemble the residual into
        """
        # PETSc.Sys.Print("Start construct b")
        # # Reset the residual vector
        # print("Call F in NonlinearProblem_mod")
        with self._b.localForm() as b_local:
            b_local.set(0.0)

        assemble_vector(self._b, self._L)

        apply_lifting(self._b, [self._a], bcs=[self.bcs], x0=[self.u.x.petsc_vec], alpha=-1.0)
        self._b.ghostUpdate(addv=PETSc.InsertMode.ADD, mode=PETSc.ScatterMode.REVERSE)
        set_bc(self._b, self.bcs, self.u.x.petsc_vec, -1.0)
        self._b.ghostUpdate(addv=PETSc.InsertMode.INSERT_VALUES, mode=PETSc.ScatterMode.FORWARD)

        self._b.copy(b)  # copy content of self._b into vector b

    def J(self, x: PETSc.Vec, A: PETSc.Mat):
        """
        Assemble the Jacobian matrix.

        Args:
            x: The vector containing the latest solution
            A: The matrix that will hold the Jacobian matrix
        """
        # print("Call J in NonlinearProblem_mod")
        # print("A shape in J: {}".format(A.getSize()))

        self._A.zeroEntries()
        assemble_matrix(self._A, self._a, self.bcs)
        self._A.assemble()

        # SNESNewtonSolver hands in self._A itself; any other matrix gets a
        # copy.
        if A.handle != self._A.handle:
            A.assemble()
            self._A.copy(A)


class SNESNewtonSolver:
    """
    Full-space Newton on PETSc SNES, driving a NonlinearProblem_mod.

    Replaces NewtonSolver_mod, which subclassed dolfinx's C++ NewtonSolver --
    deprecated since dolfinx 0.10 and slated for removal. The attribute surface
    is the old one (rtol, atol, max_it, convergence_criterion,
    relaxation_parameter, error_on_nonconvergence, krylov_solver, A, b,
    solve(u) -> (n, converged)), and the defaults below reproduce the old
    solver step for step rather than adopting SNES's own behaviour:

    * newtonls with the BASIC line search, so every step is taken in full,
      as NewtonSolver did. SNES's default (bt) would evaluate the residual at
      extra trial points, and could shorten a step the old solver took in
      full.
    * dolfinx's convergence test, not SNES's: "incremental" judges ||dx_k||
      against ||dx_1|| and never stops on the first step; "residual" judges
      ||F|| against ||F_0||. ||dx|| is the RAW Newton step, recorded before
      the step limiter rescales it.
    * a KSP that fails to converge does not stop the solve. NewtonSolver took
      the step regardless; SNES by default aborts with DIVERGED_LINEAR_SOLVE
      before taking any step (checked on this build).
    * the step limiter (set_step_limiter) replaces set_update. It runs as the
      line search's pre-check and rescales dx IN PLACE; the basic line search
      then lands on x - dx, the same step the old x.axpy(-theta, dx) took.

    Checked against NewtonSolver_mod on a nonlinear Poisson problem with
    Dirichlet BCs (1 and 3 ranks; both criteria, relaxation, a step limiter,
    max_it=1, a KSP capped short of convergence): iteration counts and
    converged flags identical, iterates equal to round-off (<= 4.4e-16). Not
    bit-identical: the Krylov solve itself differs in the last bit, from
    identical residual, settings and iteration count.

    The Jacobian is assembled straight into problem._A, which is also the
    KSP's operator. NewtonSolver_mod kept a second full-size matrix and copied
    problem._A into it every iteration.

    The SNES iterate is its own vector, not u's: the forms read u, and SNES
    evaluates the residual at a line-search work vector, so F and J copy their
    argument into u (owned entries, then a forward ghost update) before
    assembling. Handing SNES u's vector instead would let that copy overwrite
    the iterate mid-line-search under any line search other than basic.

    SNES options use the prefix `nls_solve_`, which the KSP inherits -- the
    prefix the C++ NewtonSolver gave its KSP, so every -nls_solve_* option
    set by apply_krylov_solver_settings (or on the command line) still lands.
    """
    def __init__(self, comm: MPI.Intracomm, problem: NonlinearProblem_mod,
                 options_prefix: str = "nls_solve_"):
        self.comm = comm
        self._problem = problem

        # dolfinx NewtonSolver's defaults, so a caller that sets only some of
        # these gets what it got before.
        self.rtol = 1e-9
        self.atol = 1e-10
        self.max_it = 50
        self.convergence_criterion = "residual"
        self.relaxation_parameter = 1.0
        self.error_on_nonconvergence = True

        self._step_limiter = None
        self._dx_norm = None
        self._residual0 = None

        self._x = problem.u.x.petsc_vec.duplicate()
        self._f = problem._b.duplicate()

        snes = PETSc.SNES().create(comm)
        snes.setOptionsPrefix(options_prefix)
        snes.setType(PETSc.SNES.Type.NEWTONLS)
        snes.getLineSearch().setType(PETSc.SNESLineSearch.Type.BASIC)
        snes.setFunction(self._residual, self._f)
        snes.setJacobian(self._jacobian, problem._A, problem._A)
        snes.setLineSearchPreCheck(self._precheck)
        snes.setConvergenceTest(self._converged)
        snes.setMaxLinearSolveFailures(int(np.iinfo(PETSc.IntType).max))
        # Before the caller's KSP configuration, so that configuration is the
        # last word; -nls_solve_snes_* on the command line can still override
        # the choices above.
        snes.setFromOptions()
        self._snes = snes

    # --- callbacks ------------------------------------------------------
    def _sync(self, x):
        u = self._problem.u.x.petsc_vec
        x.copy(u)
        u.ghostUpdate(addv=PETSc.InsertMode.INSERT, mode=PETSc.ScatterMode.FORWARD)
        return u

    def _residual(self, snes, x, b):
        self._problem.F(self._sync(x), b)

    def _jacobian(self, snes, x, A, P):
        self._problem.J(self._sync(x), A)

    def _precheck(self, x, dx):
        # Before the limiter touches dx: the incremental test is on the raw
        # Newton step, as it was in NewtonSolver.
        self._dx_norm = dx.norm()
        if self._step_limiter is not None:
            self._step_limiter(self, x, dx)
        elif self.relaxation_parameter != 1.0:
            dx.scale(self.relaxation_parameter)

    def _converged(self, snes, it, norms):
        _, _, fnorm = norms
        if self.convergence_criterion == "residual":
            residual = fnorm
            if it == 0:
                self._residual0 = residual
        elif self.convergence_criterion == "incremental":
            # NewtonSolver took at least one step under this criterion, and
            # measured the later steps against the first.
            if it == 0:
                return PETSc.SNES.ConvergedReason.ITERATING
            residual = self._dx_norm
            if it == 1:
                self._residual0 = residual
                return PETSc.SNES.ConvergedReason.ITERATING
        else:
            raise ValueError("convergence_criterion must be 'residual' or "
                             "'incremental', got {!r}".format(
                                 self.convergence_criterion))
        if residual < self.atol:
            return PETSc.SNES.ConvergedReason.CONVERGED_FNORM_ABS
        if self._residual0 > 0 and residual / self._residual0 < self.rtol:
            return PETSc.SNES.ConvergedReason.CONVERGED_FNORM_RELATIVE
        # max_it is enforced by SNES itself, as DIVERGED_MAX_IT.
        return PETSc.SNES.ConvergedReason.ITERATING

    # --- public API -----------------------------------------------------
    def set_step_limiter(self, limiter):
        """
        Install `limiter(solver, x, dx)`, called once per Newton step with the
        current iterate x and the Newton step dx (the solve of J dx = F).
        It must rescale dx IN PLACE to the step it wants taken: the new
        iterate is x - dx. It must not modify x. Replaces relaxation_parameter
        when set.
        """
        self._step_limiter = limiter

    def solve(self, u: _Function):
        """Solve the non-linear problem into function u. Returns the number
        of Newton iterations and whether the solver converged."""
        self._snes.setTolerances(max_it=int(self.max_it))
        u.x.petsc_vec.copy(self._x)
        self._snes.solve(None, self._x)
        self._x.copy(u.x.petsc_vec)
        u.x.scatter_forward()
        n = self._snes.getIterationNumber()
        converged = self._snes.getConvergedReason() > 0
        if not converged and self.error_on_nonconvergence:
            raise RuntimeError(
                "Newton solver did not converge ({} after {} iterations)".format(
                    self._snes.getConvergedReason(), n))
        return n, converged

    @property
    def krylov_solver(self) -> PETSc.KSP:
        """The Newton step's linear solver."""
        return self._snes.getKSP()

    @property
    def snes(self) -> PETSc.SNES:
        return self._snes

    @property
    def A(self) -> PETSc.Mat:
        """Jacobian matrix (the problem's own, not a copy)."""
        return self._problem._A

    @property
    def b(self) -> PETSc.Vec:
        """Residual vector."""
        return self._f

    def destroy(self):
        """Free the SNES and this solver's two vectors. The Jacobian belongs to
        the problem and is left alone."""
        self._snes.destroy()
        self._x.destroy()
        self._f.destroy()
